apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local
  namespace: garden-local
  annotations:
    shoot.gardener.cloud/cloud-config-execution-max-delay-seconds: "0"
spec:
  seedName: local
  cloudProfile:
    name: local
  secretBindingName: local # dummy, doesn't contain any credentials
  region: local
  purpose: testing
  extensions:
  - type: registry-cache
    providerConfig:
      apiVersion: registry.extensions.gardener.cloud/v1alpha3
      kind: RegistryConfig
      caches:
      - upstream: docker.io
        volume:
          size: 500Mi
      - upstream: ghcr.io
      - upstream: quay.io
        garbageCollection:
          ttl: 0s
  networking:
    type: calico
    # Must be within 10.0.0.0/16 (subnet of kind pod CIDR 10.0.0.0/15, but disjoint with seed pod CIDR 10.1.0.0/16).
    nodes: 10.0.0.0/16
  provider:
    type: local
    workers:
    - name: local
      machine:
        type: local
      cri:
        name: containerd
      minimum: 1
      maximum: 1
      maxSurge: 1
      maxUnavailable: 0
  kubernetes:
    version: 1.33.0
    kubelet:
      serializeImagePulls: false
      registryPullQPS: 10
      registryBurst: 20
