version: 2
updates:
# Create PRs for github.com/gardener/gardener dependency updates
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 5
  allow:
  - dependency-name: "github.com/gardener/gardener"
  labels:
  - kind/enhancement
# Create PRs for golang version updates
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: "golang"
    versions: ["*rc*"]
  labels:
  - kind/enhancement
- package-ecosystem: docker
  directory: /.test-defs
  schedule:
    interval: daily
  ignore:
  - dependency-name: "golang"
    versions: ["*rc*"]
  labels:
  - kind/enhancement
