---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: extension
build:
  artifacts:
    - image: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/registry-cache
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-registry-cache/app
            - imagevector
            - pkg/apis/config
            - pkg/apis/config/v1alpha1
            - pkg/apis/config/validation
            - pkg/apis/mirror
            - pkg/apis/mirror/install
            - pkg/apis/mirror/v1alpha1
            - pkg/apis/registry
            - pkg/apis/registry/helper
            - pkg/apis/registry/install
            - pkg/apis/registry/v1alpha3
            - pkg/cmd
            - pkg/component/registrycaches
            - pkg/component/registryconfigurationcleaner
            - pkg/constants
            - pkg/controller/cache
            - pkg/controller/mirror
            - pkg/utils/registry
            - pkg/webhook/cache
            - pkg/webhook/mirror
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-registry-cache
resourceSelector:
  allow:
    # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
    - groupKind: ControllerDeployment.core.gardener.cloud
      image: [".*"]
manifests:
  rawYaml:
    - example/controller-registration.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: admission
build:
  artifacts:
    - image: europe-docker.pkg.dev/gardener-project/public/gardener/extensions/registry-cache-admission
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-registry-cache-admission/app
            - pkg/admission/cmd
            - pkg/admission/validator/cache
            - pkg/admission/validator/helper
            - pkg/admission/validator/mirror
            - pkg/apis/mirror
            - pkg/apis/mirror/install
            - pkg/apis/mirror/v1alpha1
            - pkg/apis/mirror/validation
            - pkg/apis/registry
            - pkg/apis/registry/helper
            - pkg/apis/registry/install
            - pkg/apis/registry/v1alpha3
            - pkg/apis/registry/validation
            - pkg/constants
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-registry-cache-admission
deploy:
  helm:
    releases:
      - name: gardener-extension-registry-cache-admission
        namespace: garden
        wait: true
        chartPath: charts/admission
        setValueTemplates:
          runtime.image.repository: '{{.IMAGE_REPO_europe_docker_pkg_dev_gardener_project_public_gardener_extensions_registry_cache_admission}}'
          runtime.image.tag: '{{.IMAGE_TAG_europe_docker_pkg_dev_gardener_project_public_gardener_extensions_registry_cache_admission}}@{{.IMAGE_DIGEST_europe_docker_pkg_dev_gardener_project_public_gardener_extensions_registry_cache_admission}}'
