apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: extension
build:
  artifacts:
    - image: local-skaffold/gardener-extension-registry-cache
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-registry-cache
            - cmd/gardener-extension-registry-cache/app
            - imagevector
            - imagevector/images.yaml
            - pkg/apis/config
            - pkg/apis/config/v1alpha1
            - pkg/apis/config/validation
            - pkg/apis/mirror
            - pkg/apis/mirror/install
            - pkg/apis/mirror/v1alpha1
            - pkg/apis/registry
            - pkg/apis/registry/helper
            - pkg/apis/registry/install
            - pkg/apis/registry/v1alpha3
            - pkg/cmd
            - pkg/component/registrycaches
            - pkg/component/registrycaches/monitoring/dashboard.json
            - pkg/component/registrycaches/templates/config.yml.tpl
            - pkg/component/registrycacheservices
            - pkg/constants
            - pkg/controller/cache
            - pkg/controller/mirror
            - pkg/secrets
            - pkg/utils/registry
            - pkg/webhook/cache
            - pkg/webhook/mirror
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-registry-cache
  insecureRegistries:
    - garden.local.gardener.cloud:5001
  tagPolicy:
    customTemplate:
      template: '{{.version}}-{{.sha}}'
      components:
        - name: version
          envTemplate:
            template: '{{.EXTENSION_VERSION}}'
        # inputDigest is used to inject a digest of the artifact source into the built image tag
        # and therefore into the SKAFFOLD_IMAGE environment variable which is used when generating the corresponding ControllerDeployment
        - name: sha
          inputDigest: {}
manifests:
  kustomize:
    paths:
      - local-setup
deploy:
  # --server-side apply is a workaround for https://github.com/gardener/gardener/issues/10267.
  # kubectl apply attempts a strategic merge patch which fails for a ControllerDeployment.
  # For more details, see https://github.com/gardener/gardener/issues/10267.
  #
  # TODO: Switch back to "kubectl: {}" when the above issue is resolved.
  kubectl:
    flags:
      apply:
        - --server-side
        - --force-conflicts
resourceSelector:
  # instruct skaffold to inject the built image reference into the image field in our ControllerDeployment
  allow:
    - groupKind: ControllerDeployment.core.gardener.cloud
      image:
        - .helm.values.image.ref
---
apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: admission
build:
  artifacts:
    - image: local-skaffold/gardener-extension-registry-cache-admission
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-registry-cache-admission
            - cmd/gardener-extension-registry-cache-admission/app
            - pkg/admission/cmd
            - pkg/admission/validator/cache
            - pkg/admission/validator/helper
            - pkg/admission/validator/mirror
            - pkg/apis/mirror
            - pkg/apis/mirror/install
            - pkg/apis/mirror/v1alpha1
            - pkg/apis/mirror/validation
            - pkg/apis/registry
            - pkg/apis/registry/helper
            - pkg/apis/registry/install
            - pkg/apis/registry/v1alpha3
            - pkg/apis/registry/validation
            - pkg/constants
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-registry-cache-admission
  insecureRegistries:
    - garden.local.gardener.cloud:5001
deploy:
  helm:
    releases:
      - name: gardener-extension-registry-cache-admission-appl # gardener-extension-registry-cache-admission-application would be too long as release name
        chartPath: charts/admission/charts/application
        namespace: garden
        setValueTemplates:
          gardener.virtualCluster.enabled: "false"
        wait: true
      - name: gardener-extension-registry-cache-admission-runtime
        chartPath: charts/admission/charts/runtime
        namespace: garden
        setValueTemplates:
          gardener.virtualCluster.enabled: "false"
          image.repository: '{{.IMAGE_REPO_local_skaffold_gardener_extension_registry_cache_admission}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_gardener_extension_registry_cache_admission}}@{{.IMAGE_DIGEST_local_skaffold_gardener_extension_registry_cache_admission}}'
        wait: true
profiles:
  - name: remote-extensions
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValues
        value:
          vpa.enabled: false
