---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: extension
build:
  insecureRegistries:
    - garden.local.gardener.cloud:5001
  artifacts:
    - image: local-skaffold/gardener-extension-registry-cache
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-registry-cache
            - cmd/gardener-extension-registry-cache/app
            - imagevector
            - imagevector/images.yaml
            - pkg/apis/config
            - pkg/apis/config/v1alpha1
            - pkg/apis/config/validation
            - pkg/apis/mirror
            - pkg/apis/mirror/install
            - pkg/apis/mirror/v1alpha1
            - pkg/apis/registry
            - pkg/apis/registry/helper
            - pkg/apis/registry/install
            - pkg/apis/registry/v1alpha3
            - pkg/cmd
            - pkg/component/registrycaches
            - pkg/component/registrycaches/monitoring/dashboard.json
            - pkg/component/registrycaches/templates/config.yml.tpl
            - pkg/constants
            - pkg/controller/cache
            - pkg/controller/mirror
            - pkg/utils/registry
            - pkg/webhook/cache
            - pkg/webhook/mirror
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-registry-cache
      hooks:
        after:
          - command: 
            - bash 
            - hack/generate-kustomize-patch-controllerdeployment-registry-cache.sh
manifests:
  kustomize:
    paths:
    - local-setup
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: admission
build:
  insecureRegistries:
    - garden.local.gardener.cloud:5001
  artifacts:
    - image: local-skaffold/gardener-extension-registry-cache-admission
      ko:
        dependencies:
          paths:
            - cmd/gardener-extension-registry-cache-admission
            - cmd/gardener-extension-registry-cache-admission/app
            - pkg/admission/cmd
            - pkg/admission/validator/cache
            - pkg/admission/validator/helper
            - pkg/admission/validator/mirror
            - pkg/apis/mirror
            - pkg/apis/mirror/install
            - pkg/apis/mirror/v1alpha1
            - pkg/apis/mirror/validation
            - pkg/apis/registry
            - pkg/apis/registry/helper
            - pkg/apis/registry/install
            - pkg/apis/registry/v1alpha3
            - pkg/apis/registry/validation
            - pkg/constants
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/gardener-extension-registry-cache-admission
deploy:
  helm:
    releases:
      - name: gardener-extension-registry-cache-admission
        namespace: garden
        wait: true
        chartPath: charts/admission
        setValueTemplates:
          global.image.repository: '{{.IMAGE_REPO_local_skaffold_gardener_extension_registry_cache_admission}}'
          global.image.tag: '{{.IMAGE_TAG_local_skaffold_gardener_extension_registry_cache_admission}}@{{.IMAGE_DIGEST_local_skaffold_gardener_extension_registry_cache_admission}}'
profiles:
- name: remote-extensions
  patches:
  - op: add
    path: /deploy/helm/releases/0/setValues
    value:
      global.vpa.enabled: false