---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: extension
build:
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/extensions/registry-cache
    ko:
      main: ./cmd/gardener-extension-registry-cache
deploy:
  helm:
    releases:
    - name: gardener-extension-registry-cache-registration
      chartPath: charts/registration
      artifactOverrides:
        values:
          image: eu.gcr.io/gardener-project/gardener/extensions/registry-cache
      imageStrategy:
        helm: {}
