---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: admission
build:
  artifacts:
  - image: eu.gcr.io/gardener-project/gardener/extensions/registry-cache-admission
    ko:
      main: ./cmd/gardener-extension-registry-cache-admission
deploy:
  helm:
    releases:
    - name: gardener-extension-registry-cache-admission
      chartPath: charts/admission
      namespace: garden
      artifactOverrides:
        global:
          image: eu.gcr.io/gardener-project/gardener/extensions/registry-cache-admission
      imageStrategy:
        helm: {}
      valuesFiles:
      - example/admission/values.yaml
