apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../example

patches:
- patch: |
    - op: replace
      path: /spec/deployment
      value:
        admission:
          runtimeCluster:
            helm:
              ociRepository:
                ref: local-skaffold/gardener-extension-registry-cache-admission/charts/runtime
          virtualCluster:
            helm:
              ociRepository:
                ref: local-skaffold/gardener-extension-registry-cache-admission/charts/application
        extension:
          helm:
            ociRepository:
              ref: local-skaffold/gardener-extension-registry-cache/charts/extension
  target:
    group: operator.gardener.cloud
    kind: Extension
    name: extension-registry-cache
- patch: |-
    $patch: delete
    apiVersion: core.gardener.cloud/v1
    kind: ControllerDeployment
    metadata:
      name: extension-registry-cache
- patch: |-
    $patch: delete
    apiVersion: core.gardener.cloud/v1beta1
    kind: ControllerRegistration
    metadata:
      name: extension-registry-cache