apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example

patches:
- patch: |
    - op: replace
      path: /providerConfig/values/image
      value: local-skaffold/gardener/extensions/registry-cache
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: extension-registry-cache
