apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../example

patches:
- patch: |
    - op: replace
      path: /helm/values
      value:
        image:
          ref: local-skaffold/gardener-extension-registry-cache
  target:
    group: core.gardener.cloud
    kind: ControllerDeployment
    name: extension-registry-cache
