apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-registry-cache
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  resources:
  - kind: Extension
    type: registry-cache
  - kind: Extension
    type: registry-mirror
  deployment:
    extension:
      helm:
        ociRepository:
          ref: local-skaffold/gardener-extension-registry-cache/charts/extension
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: local-skaffold/gardener-extension-registry-cache-admission/charts/runtime
      virtualCluster:
        helm:
          ociRepository:
            ref: local-skaffold/gardener-extension-registry-cache-admission/charts/application
