apiVersion: testmachinery.sapcloud.io
kind: TestDefinition
metadata:
  name: registry-cache-serial-test-suite
spec:
  owner: gardener-oq@listserv.sap.com
  description: registry-cache extension test suite that includes all serial tests

  activeDeadlineSeconds: 13200
  behavior:
  - serial

  command: [bash, -c]
  args:
    - >-
      go test -timeout=0 ./test/testmachinery/shoot
      --v -ginkgo.v -ginkgo.show-node-events -ginkgo.no-color
      -kubecfg=$TM_KUBECONFIG_PATH/gardener.config
      -project-namespace=$PROJECT_NAMESPACE
      -shoot-name=$SHOOT_NAME
      -ginkgo.focus="\[SERIAL\]"
      -ginkgo.skip="\[DISRUPTIVE\]"
      -ginkgo.timeout=9000s

  image: golang:1.24.7
