#!/usr/bin/env bash

# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

"$(dirname $0)"/third_party/component_descriptor "$(dirname $0)"/..
