#!/usr/bin/env bash

# TODO(ialidzhikov): Remove the COMPONENT_PREFIXES env var once gardener/gardener@v1.87 (contains https://github.com/gardener/gardener/pull/9008) is vendored.
COMPONENT_PREFIXES="europe-docker.pkg.dev/gardener-project/releases/gardener" \
  "$(dirname $0)"/../vendor/github.com/gardener/gardener/hack/.ci/component_descriptor "$(dirname $0)"/..
