apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gardener-extension-registry-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-registry-cache
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-registry-cache
      app.kubernetes.io/instance: {{ .Release.Name }}
