---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gardener-extension-registry-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-registry-cache
    helm.sh/chart: gardener-extension-registry-cache
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gardener-extension-registry-cache
subjects:
- kind: ServiceAccount
  name: gardener-extension-registry-cache
  namespace: {{ .Release.Namespace }}
