---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gardener-extension-registry-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-registry-cache
    helm.sh/chart: gardener-extension-registry-cache
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - {{ include "leaderelectionid" . }}
  - gardener-extension-heartbeat
  verbs:
  - update
  - get
