{{- if .Values.vpa.enabled}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gardener-extension-registry-cache-vpa
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.vpa.resourcePolicy }}
  resourcePolicy:
    containerPolicies:
    - containerName: gardener-extension-registry-cache
      {{- with .Values.vpa.resourcePolicy.minAllowed }}
      minAllowed: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vpa.resourcePolicy.maxAllowed }}
      maxAllowed: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.vpa.resourcePolicy.controlledValues }}
      controlledValues: {{ .Values.vpa.resourcePolicy.controlledValues }}
      {{- end }}
  {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gardener-extension-registry-cache
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- end }}
