{{- if .Values.vpa.enabled}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gardener-extension-registry-cache-vpa
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.vpa.resourcePolicy }}
  resourcePolicy:
    containerPolicies:
      - containerName: gardener-extension-registry-cache
        minAllowed:
          memory: {{ required ".Values.vpa.resourcePolicy.minAllowed.memory is required" .Values.vpa.resourcePolicy.minAllowed.memory }}
        maxAllowed:
          cpu: {{ required ".Values.vpa.resourcePolicy.maxAllowed.cpu is required" .Values.vpa.resourcePolicy.maxAllowed.cpu }}
          memory: {{ required ".Values.vpa.resourcePolicy.maxAllowed.memory is required" .Values.vpa.resourcePolicy.maxAllowed.memory }}
        controlledValues: RequestsOnly
  {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gardener-extension-registry-cache
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- end }}
