name: Prepare Release

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v7
      with:
        go-version: stable
    - name: Run 'make generate'
      shell: bash
      run: |
        set -eu
        make generate
